.در سلول زیر، تابعی برای محاسبه‌ی بازگشتی دترمینان تعریف کنید

In [12]:
import numpy as np
x = np.array([[1,2,3] , [4,5,3] , [2,8,9]])
def determinat(a):
    if len(a) == 1:
        return a[0][0]
    elif len(a) == 2:
        return a[0][0] * a[1][1] - a[0][1] * a[1][0]
    else:
        determinal = 0
        for i in range(len(a)):
            main_result = []
            pow = (-1) ** i
            for j in range(1, len(a)):
                result = []
                for k in range(len(a)):
                    if k != i:
                        result.append(a[j][k])        
                main_result.append(result)
            determinal += pow * a[0][i] * determinat(main_result)
    return determinal
print(determinat(x))

27


.در سلول زیر قانون کرامر را در تابعی پیاده‌سازی کنید

In [16]:
def cramer(matrix, result):
    det = determinat(matrix)
    if det == 0:
        return "The system has no unique solution"
    n = len(matrix[0])
    solutions = []
    for i in range(n):
        matrix_copy = matrix.copy()
        matrix_copy[:,i] = result
        solutions.append(round(np.linalg.det(matrix_copy)/det,2))
    return solutions


	T(cX)=cT(X)

In [6]:
import numpy as np
x = np.array([[2, 3] , [0 , 2] , [1 , 4] , [3 , 0]] )
Tx = np.transpose(x)
c = 3

cx = c * x
cTX = c * Tx
TcX = np.transpose(cx)
assert np.array_equal(TcX, cTX)
print(cTX)
print(TcX)

[[ 6  0  3  9]
 [ 9  6 12  0]]
[[ 6  0  3  9]
 [ 9  6 12  0]]


	T(u+v)=T(u)+T(v)

In [7]:
import numpy as np
u = np.array([[2 , 3] , [0 , 3] , [2 , 3] , [2 , 2]] )
v = np.array([[1 , 4] , [4 , 0] , [1 , 5] , [1 , 7]])
 
Tu = np.transpose(u)
Tv = np.transpose(v)
Tuv1 = np.transpose(u+v)
Tuv2 = Tu + Tv
assert np.allclose(Tuv1, Tuv2)
print(Tuv1)
print(Tuv2)

[[3 4 3 3]
 [7 3 8 9]]
[[3 4 3 3]
 [7 3 8 9]]
